# Generated by Django 5.2.1 on 2025-06-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="acc_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("phone", models.PositiveIntegerField()),
                ("aadhar", models.PositiveIntegerField()),
                ("dob", models.DateField()),
                ("address", models.TextField()),
                ("acc_no", models.PositiveIntegerField(default=1200)),
                ("pin", models.PositiveIntegerField(default=0)),
                ("amount", models.PositiveIntegerField(default=500)),
                (
                    "acc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.acc_type"
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.gender"
                    ),
                ),
            ],
        ),
    ]
